volumes:
  bundle_path_store_web_sapiencia5:

services:
  store_web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/sapiencia5/app:cached
      - ./entrypoint.sh:/home/sapiencia5/app/entrypoint.sh:ro
      - bundle_path_store_web_sapiencia5:/usr/local/bundle
    command: bundle exec rails server -b 0.0.0.0
