volumes:
  bundle_path_store_web_sapiencia:

services:
  store_web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/sapiencia/app:cached
      - ./entrypoint.sh:/home/sapiencia/app/entrypoint.sh:ro
      - bundle_path_store_web_sapiencia:/usr/local/bundle
    command: bundle exec rails server -b 0.0.0.0