# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 633f601df55f544d2fdb80680f8c75d9ca8880a196e0f09340525176ea42a2f1f5b258405c44c3e533f71db440b84e3d78dab0c1b63f1df4bf9dc86a1f2ecf61

test:
  secret_key_base: 886bde44ca4171406bf17e25600ce97e62f073f9128eb75f006cd92015e9334ecf47ee101fa98ef2fb816e04854e5da291e5fc9e2b07e197cb74d16026af0977
  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2eb8ceeaf09042a4edda0c6dc8d8b564674f76bed3780bd220b4bd208e123823bc2b5254c40b0be9278029694b389e569ee17f1516a349a545663be7a6331e2b
  slack_url: <%= ENV["SLACK"] %>

webpush:
  public_key: <%= ENV["VAPID_PUBLIC_KEY"] %>
  private_key: <%= ENV["VAPID_PRIVATE_KEY"] %>